version: '3.1'
services:
  backend-tech-test:
    build: .
    container_name: backend-tech-test
    ports:
      - "5071:5071"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:15.4
    container_name: postgresdb
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=phorest
      - POSTGRES_USER=phorest
      - POSTGRES_PASSWORD=phorest